### ISSUE TITLE
Derive `Deserialize` trait for `CreateCompletionRequest`

### ISSUE THREAD

**Issue by dr497** [64bit/async-openai#109]
Currently the `Deserialize` trait is not derived for `CreateCompletionRequest` https://github.com/64bit/async-openai/blob/main/async-openai/src/types/types.rs#L53

Deriving it would make it easier to compose with this awesome crate

**Comment by 64bit** [comment]
I think most of the request structs do not have `Deserialize` because they primarily are needed to send request via `Serialize`, contributors in the past added `Deserialize` for I think chat where they need to create request from json/file. 

The completion API is now marked legacy and favors chat completion in the API reference/guides. That said, PR is welcome!

**Comment by 64bit** [comment]
The OpenAI recommened Chat endpoints does have deserialization support. Since Completions is now considered legacy I'm closing this, but if its a dealbreak please feel free to leave comment or reopen.
