### ISSUE TITLE
Question: OpenAI assistant/thread support

### ISSUE THREAD

**Issue by jeremychone** [64bit/async-openai#132]
Any plan for the new OpenAI assistant/thread API ? 

https://platform.openai.com/docs/assistants/overview

**Comment by 64bit** [comment]
Hopefully soon, Its a really big release today.

**Comment by jeremychone** [comment]
Yes, today was significant and placed the entire OpenAI platform in a different league.

**Comment by 64bit** [comment]
Hello, I just published a new release v0.16.0 for updates from DevDay. Please give it a try, if you find any issues PRs are most welcome!

**Comment by jeremychone** [comment]
@64bit Cool, let me give it a try.

**Comment by jeremychone** [comment]
Ok, I did a very preliminary test with list assistants and it works. The API is clean and well-designed. This is awesome.

I will work on using it more in the next few weeks and will report back here. By the way, feel free to close this issue if you want.

**Comment by 64bit** [comment]
Thank you 😌 

Please pardon if there are few hiccups along the way, this release made sure to have all the machinery required for new APIs in short time but not enough working examples for testing. 

In the meantime we can close this since we have an answer for original question. You're welcome to continue conversation here or create new issue should they arise.

**Comment by jeremychone** [comment]
@64bit This is awesome, way faster than I expected.

I'll report any issues (in new tickets) or add PRs if I notice anything.
