### ISSUE TITLE
The method of deleting fine-tuning model is not implemented

### ISSUE THREAD

**Issue by rtmyway** [64bit/async-openai#40]

**Comment by 64bit** [comment]
Hello, 

Its actually implemented here: https://docs.rs/async-openai/latest/async_openai/struct.Models.html#method.delete 

Its not implemented under [FineTunes](https://docs.rs/async-openai/latest/async_openai/struct.FineTunes.html) because the [REST endpoint](https://platform.openai.com/docs/api-reference/fine-tunes/delete-model) is `delete https://api.openai.com/v1/models/{model}`
